disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "LM Art Studio"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "logo-mini.png"

[params.author]
name = "LM Art Studio"
image = "logo.png"
